import "./bootstrap";
// import scrollAnimation from "./directives/scrollAnimation";
import { createApp } from "vue";
import { createPinia } from "pinia";
import "../css/app.css";
import App from "./App.vue";
import router from "./router";
const pinia = createPinia();
const app = createApp(App);
app.use(router);
app.use(pinia);
// app.directive("scrollAnimation", scrollAnimation);
app.mount("#app");
